name: afforable_housing
description: A new Flutter project.

dependencies:
  flutter:
    assets:
          - assets/option1.png
          - assets/option2.png
          - assets/option3.png
          - assets/option4.png
          - assets/option5.png
          - assets/Apartment.png
          - assets/House.png
          - assets/Townhouse.png
    sdk: flutter



  cupertino_icons: ^0.1.0

  image_carousel: "^0.4.0+1"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
